language: java

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw compile jib:dockerBuild

after_script:
  - docker images

before_deploy:
  - docker tag "$IMAGE_NAME:latest" "${IMAGE_NAME}:${TRAVIS_TAG}"
  - docker images
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true